// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvPuBmG4W-WoetAdidWREuJ02MG7X5bfI',
    appId: '1:100103282418:web:4967e88f51b5a16a4cba6b',
    messagingSenderId: '100103282418',
    projectId: 'chatapp-f397c',
    authDomain: 'chatapp-f397c.firebaseapp.com',
    storageBucket: 'chatapp-f397c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE240fT_TfyfSfNVSkjyOCFBbI5t0RtsA',
    appId: '1:100103282418:android:b0fed768b4b7aa2a4cba6b',
    messagingSenderId: '100103282418',
    projectId: 'chatapp-f397c',
    storageBucket: 'chatapp-f397c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJnOg42OblIjlL3fVijgyucL1VPRxkqY',
    appId: '1:100103282418:ios:d7ea922560098a4c4cba6b',
    messagingSenderId: '100103282418',
    projectId: 'chatapp-f397c',
    storageBucket: 'chatapp-f397c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJnOg42OblIjlL3fVijgyucL1VPRxkqY',
    appId: '1:100103282418:ios:d7ea922560098a4c4cba6b',
    messagingSenderId: '100103282418',
    projectId: 'chatapp-f397c',
    storageBucket: 'chatapp-f397c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvPuBmG4W-WoetAdidWREuJ02MG7X5bfI',
    appId: '1:100103282418:web:c12b58b8ae66b0514cba6b',
    messagingSenderId: '100103282418',
    projectId: 'chatapp-f397c',
    authDomain: 'chatapp-f397c.firebaseapp.com',
    storageBucket: 'chatapp-f397c.firebasestorage.app',
  );
}
